project_id = "dszyyrcvwrpyiypwyvxe"

[functions.push-subscriptions]
verify_jwt = true

[functions.push-send]
verify_jwt = true

[functions.push-process]
verify_jwt = false

[functions.smart-summary]
verify_jwt = true

[functions.met-forecast]
verify_jwt = false
entrypoint = "./functions/met-forecast/index.js"

[functions.lightning]
verify_jwt = false
entrypoint = "./functions/lightning/index.js"
