project_id = "dszyyrcvwrpyiypwyvxe"

[functions.push-subscriptions]
verify_jwt = true

[functions.push-send]
verify_jwt = true

[functions.push-process]
verify_jwt = false

[functions.smart-summary]
verify_jwt = true
