const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, 'dist', file), 'utf8');
const html = read('index.html');
const app = read('app.js');
const p0 = read('p0.js');
const sw = read('sw.js');
const radarProbe = read('modules/radar-probe.js');
const weatherServices = read('modules/weather-services.js');
const manifest = JSON.parse(read('manifest.webmanifest'));

assert(!html.includes('municipalities.js'), 'municípios não podem bloquear o primeiro paint');
assert(!html.includes('auth.js') && !html.includes('authDialog'), 'o painel público não deve carregar login');
assert.match(html, /id="citySearch"[^>]+aria-autocomplete="list"/);
assert.match(html, /id="openCitySearch"[\s\S]+id="selectedCityLabel"/);
assert.match(p0, /setTimeout\([\s\S]+1500\)/, 'Manaus precisa abrir em até 1,5 s');
assert.match(html, /sessionStorage/, 'a introdução deve aparecer uma vez por sessão');
assert.doesNotMatch(html, /id="skipIntro"|class="skip-intro"/);
assert.match(html, /class="intro-sky"[\s\S]*?class="intro-sun"[\s\S]*?class="intro-rain"/);
assert.match(html, /class="intro-wordmark"[\s\S]*?<strong>PLUVIA<\/strong>/);
assert.doesNotMatch(html, /pluvia-footer-logo\.jpeg/);
assert.match(html, /class="intro-progress"/);
assert.match(html, /setTimeout\(dismiss, reduced \? 300 : 3400\)/);
assert.match(html, /prefers-reduced-motion: reduce/);
assert.match(app, /ponto de referência a cerca de/);
assert.match(app, /Sem chuva agora; previsão de chuva/);
assert.match(app, /Prioridade definida pelo aviso oficial do INMET/);
assert.match(html, /MAPA DO TEMPO[\s\S]*Radar observado e estimativa da cobertura de nuvens\./i);
assert.match(html, /id="openWeatherMap"[^>]*>Abrir mapa/);
assert.match(app, /prefers-reduced-motion: reduce/);
assert.match(html, /summary_large_image/);
assert.match(html, /og-pluvia\.png/);
assert.match(html, /family=Nunito:wght@400;500;600;700;800;900/);
assert.doesNotMatch(html, /family=Manrope|family=DM\+Mono/);
const styles = read('styles.css');
assert.match(styles, /--font-ui:\s*"Nunito", ui-rounded, system-ui, sans-serif/);
assert.doesNotMatch(styles, /Manrope|DM Mono/);
assert.match(html, /class="footer-brand"[\s\S]*?<strong>PLUVIA<\/strong><span>O céu de cada cidade<\/span>/);
assert.doesNotMatch(html, /<section class="sobre|id="sobre"/);
assert.doesNotMatch(html, /<p>PLUVIA · O céu de cada cidade\.<\/p>/);
assert.doesNotMatch(sw, /assets\/pluvia-footer-logo\.jpeg/);
assert.doesNotMatch(html, /MODELO DE PRECIPITAÇÃO|Pulso de chuva no município|id="rainPulse|id="rainMap/);
assert.doesNotMatch(app, /rainPulse|rainMapLocations|getPrecipitationGrid|Comparando nove pontos ao redor/);
assert.match(app, /não verifica automaticamente os alertas da Defesa Civil/);
assert(!sw.slice(0, sw.indexOf('self.addEventListener("activate"')).includes('municipalities.js'), 'a lista completa não deve entrar no precache');
assert.match(sw, /endsWith\("\/municipalities\.js"\)/, 'municípios devem usar cache imutável depois da primeira busca');
assert.match(sw, /pluvia-core-101/);
assert.match(html, /id="weatherView" class="initial-loading" aria-busy="true"/);
assert.match(html, /viewport-fit=cover/);
assert.match(html, /styles\.css\?v=core-101/);
assert.match(html, /modules\/weather-icon-system\.js\?v=vector-1/);
assert.match(sw, /assets\/weather-icons\/conditions\/clear-day\.svg/);
assert.match(html, /id="openWeatherMap"/);
assert.match(html, /data-weather-layer="rain"[\s\S]+data-weather-layer="clouds"/);
assert.doesNotMatch(html, /data-weather-layer="satellite"/);
assert.doesNotMatch(html, /id="goOutCard"|PLUVIA SINAL · DÁ PRA SAIR\?|Por que este sinal\?/);
assert.doesNotMatch(app, /renderGoOut/);
assert.match(sw, /weather-map\.js\?v=core-101/);
assert.doesNotMatch(html, /modules\/signal\.js/);
assert.match(html, /RESUMO INTELIGENTE/);
assert.doesNotMatch(html, /id="smokeCard"|FUMAÇA E PARTÍCULAS/);
assert.match(html, /id="windCompass"/);
assert.match(app, /applyWeatherAtmosphere/);
assert.match(app, /hour-temp/);
assert(manifest.icons.some(icon => icon.sizes === '192x192' && icon.purpose === 'any'));
assert(manifest.icons.some(icon => icon.sizes === '512x512' && icon.purpose === 'any'));
assert(manifest.icons.some(icon => icon.sizes === '512x512' && icon.purpose === 'maskable'));
assert(manifest.icons.some(icon => icon.sizes === '192x192' && icon.purpose === 'maskable'));
assert.equal(manifest.background_color, '#10233f');
assert.match(html, /apple-touch-icon-180\.png/);
assert.match(html, /apple-mobile-web-app-status-bar-style" content="black-translucent"/);
assert.match(html, /modules\/weather-data-layer\.js\?v=core-101/);
assert.match(html, /modules\/http-client\.js\?v=core-67/);
assert.match(html, /modules\/weather-services\.js\?v=core-101/);
assert.match(html, /modules\/weather-insights\.js\?v=core-64/);
assert.match(html, /app\.js\?v=core-101/);
assert.match(html, /modules\/radar-probe\.js\?v=core-70/);
assert.match(html, /pluviaweather\.com\.br/);
assert.match(app, /prefetchForecast/);
assert.match(app, /Atualizando… · leitura salva/);
assert.ok(app.indexOf('sources.set("alerts",{status:"ready"') < app.indexOf('renderInmetAlerts(raw);'), 'INMET must be ready before alert render repaints the signal');
assert.match(app, /radar\?\.reset\?\.\(city\.id\)/);
assert.match(app, /services\?\.abortAll\(\)/);
assert.doesNotMatch(app, /api\.open-meteo\.com|apiprevmet3\.inmet\.gov\.br|wp-json\/wp\/v2\/posts/);
assert.match(weatherServices, /api\.open-meteo\.com/);
assert.match(weatherServices, /apiprevmet3\.inmet\.gov\.br/);
assert.match(weatherServices, /past_hours:"24"/);
assert.match(radarProbe, /app\.http\?\.createClient/);
assert.doesNotMatch(radarProbe, /await fetch\(/);
assert.match(html, /id="weatherExplanation"/);

console.log('PASS product shell: public first paint, 1.5 s fallback, lazy municipalities, honest point data and versioned offline shell.');
