const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, 'dist', file), 'utf8');
const html = read('index.html');
const app = read('app.js');
const p0 = read('p0.js');
const sw = read('sw.js');
const manifest = JSON.parse(read('manifest.webmanifest'));

assert(!html.includes('municipalities.js'), 'municípios não podem bloquear o primeiro paint');
assert(!html.includes('auth.js') && !html.includes('authDialog'), 'o painel público não deve carregar login');
assert.match(html, /id="citySearch"[^>]+aria-autocomplete="list"/);
assert.match(html, /id="openCitySearch"[\s\S]+id="selectedCityLabel"/);
assert.match(p0, /setTimeout\([\s\S]+1500\)/, 'Manaus precisa abrir em até 1,5 s');
assert.match(p0, /sessionStorage/, 'a introdução deve aparecer uma vez por sessão');
assert.match(app, /O clima é do ponto do município|Não é a sua rua/);
assert.match(app, /Ainda seco, mas pode vir/);
assert.match(app, /Prioridade definida pelo aviso oficial do INMET/);
assert.match(html, /não radar nem chuva na sua rua/i);
assert.match(app, /prefers-reduced-motion: reduce/);
assert.match(html, /summary_large_image/);
assert.match(html, /og-pluvia\.png/);
assert.match(app, /Comparando nove pontos ao redor/);
assert.match(app, /Volume previsto sozinho não vira alerta/);
assert.match(app, /Defesa Civil Nacional/);
assert(!sw.slice(0, sw.indexOf('self.addEventListener("activate"')).includes('municipalities.js'), 'a lista completa não deve entrar no precache');
assert.match(sw, /endsWith\("\/municipalities\.js"\)/, 'municípios devem usar cache imutável depois da primeira busca');
assert.match(sw, /pluvia-core-46/);
assert.match(html, /id="openWeatherMap"/);
assert.match(html, /data-weather-layer="rain"[\s\S]+data-weather-layer="satellite"[\s\S]+data-weather-layer="clouds"/);
assert.match(html, /id="goOutCard"/);
assert.match(app, /renderGoOut/);
assert.match(sw, /weather-map\.js\?v=core-46/);
assert.match(html, /PLUVIA SINAL · DÁ PRA SAIR\?/);
assert.match(html, /Por que este sinal\?/);
assert.match(html, /modules\/signal\.js\?v=core-46/);
assert.match(html, /AGORA NO PLUVIA/);
assert.match(html, /id="windCompass"/);
assert.match(app, /applyWeatherAtmosphere/);
assert.match(app, /hour-temp/);
assert(manifest.icons.some(icon => icon.sizes === '192x192' && icon.purpose === 'any'));
assert(manifest.icons.some(icon => icon.sizes === '512x512' && icon.purpose === 'any'));
assert(manifest.icons.some(icon => icon.sizes === '512x512' && icon.purpose === 'maskable'));

console.log('PASS product shell: public first paint, 1.5 s fallback, lazy municipalities, honest point data and versioned offline shell.');
