const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, 'dist', file), 'utf8');
const html = read('index.html');
const app = read('app.js');
const p0 = read('p0.js');
const sw = read('sw.js');
const radarProbe = read('modules/radar-probe.js');
const weatherServices = read('modules/weather-services.js');
const manifest = JSON.parse(read('manifest.webmanifest'));

assert(!html.includes('municipalities.js'), 'municípios não podem bloquear o primeiro paint');
assert(!html.includes('auth.js') && !html.includes('authDialog'), 'o painel público não deve carregar login');
assert.match(html, /id="citySearch"[^>]+aria-autocomplete="list"/);
assert.match(html, /id="openCitySearch"[\s\S]+id="selectedCityLabel"/);
assert.match(p0, /setTimeout\([\s\S]+1500\)/, 'Manaus precisa abrir em até 1,5 s');
assert.match(p0, /sessionStorage/, 'a introdução deve aparecer uma vez por sessão');
assert.match(app, /O clima é do ponto do município|Não é a sua rua/);
assert.match(app, /Ainda seco, mas pode vir/);
assert.match(app, /Prioridade definida pelo aviso oficial do INMET/);
assert.match(html, /Radar quando houver cobertura, satélite com data visível e nuvens estimadas pelo modelo/i);
assert.match(app, /prefers-reduced-motion: reduce/);
assert.match(html, /summary_large_image/);
assert.match(html, /og-pluvia\.png/);
assert.doesNotMatch(html, /MODELO DE PRECIPITAÇÃO|Pulso de chuva no município|id="rainPulse|id="rainMap/);
assert.doesNotMatch(app, /rainPulse|rainMapLocations|getPrecipitationGrid|Comparando nove pontos ao redor/);
assert.match(app, /Defesa Civil Nacional/);
assert(!sw.slice(0, sw.indexOf('self.addEventListener("activate"')).includes('municipalities.js'), 'a lista completa não deve entrar no precache');
assert.match(sw, /endsWith\("\/municipalities\.js"\)/, 'municípios devem usar cache imutável depois da primeira busca');
assert.match(sw, /pluvia-core-71/);
assert.match(html, /id="weatherView" class="initial-loading" aria-busy="true"/);
assert.match(html, /viewport-fit=cover/);
assert.match(html, /styles\.css\?v=core-71/);
assert.match(html, /modules\/weather-icon-system\.js\?v=glossy-2/);
assert.match(sw, /assets\/weather-icons\/conditions\/clear-day\.png/);
assert.match(html, /id="openWeatherMap"/);
assert.match(html, /data-weather-layer="rain"[\s\S]+data-weather-layer="satellite"[\s\S]+data-weather-layer="clouds"/);
assert.doesNotMatch(html, /id="goOutCard"|PLUVIA SINAL · DÁ PRA SAIR\?|Por que este sinal\?/);
assert.doesNotMatch(app, /renderGoOut/);
assert.match(sw, /weather-map\.js\?v=core-68/);
assert.doesNotMatch(html, /modules\/signal\.js/);
assert.match(html, /RESUMO INTELIGENTE/);
assert.match(html, /id="windCompass"/);
assert.match(app, /applyWeatherAtmosphere/);
assert.match(app, /hour-temp/);
assert(manifest.icons.some(icon => icon.sizes === '192x192' && icon.purpose === 'any'));
assert(manifest.icons.some(icon => icon.sizes === '512x512' && icon.purpose === 'any'));
assert(manifest.icons.some(icon => icon.sizes === '512x512' && icon.purpose === 'maskable'));
assert(manifest.icons.some(icon => icon.sizes === '192x192' && icon.purpose === 'maskable'));
assert.equal(manifest.background_color, '#075dff');
assert.match(html, /apple-touch-icon-180\.png/);
assert.match(html, /apple-mobile-web-app-status-bar-style" content="black-translucent"/);
assert.match(html, /modules\/weather-data-layer\.js\?v=core-66/);
assert.match(html, /modules\/http-client\.js\?v=core-67/);
assert.match(html, /modules\/weather-services\.js\?v=core-71/);
assert.match(html, /modules\/weather-insights\.js\?v=core-64/);
assert.match(html, /app\.js\?v=core-71/);
assert.match(html, /modules\/radar-probe\.js\?v=core-70/);
assert.match(html, /pluviaweather\.com\.br/);
assert.match(app, /prefetchForecast/);
assert.match(app, /Atualizando… · leitura salva/);
assert.ok(app.indexOf('sources.set("alerts",{status:"ready"') < app.indexOf('renderInmetAlerts(raw);'), 'INMET must be ready before alert render repaints the signal');
assert.match(app, /radar\?\.reset\?\.\(city\.id\)/);
assert.match(app, /services\?\.abortAll\(\)/);
assert.doesNotMatch(app, /api\.open-meteo\.com|apiprevmet3\.inmet\.gov\.br|wp-json\/wp\/v2\/posts/);
assert.match(weatherServices, /api\.open-meteo\.com/);
assert.match(weatherServices, /apiprevmet3\.inmet\.gov\.br/);
assert.match(weatherServices, /past_hours:"24"/);
assert.match(radarProbe, /app\.http\?\.createClient/);
assert.doesNotMatch(radarProbe, /await fetch\(/);
assert.match(html, /id="weatherExplanation"/);

console.log('PASS product shell: public first paint, 1.5 s fallback, lazy municipalities, honest point data and versioned offline shell.');
